# if there's a new tag, check if there's a branch called F-Droid in GitLab, then delete it if there is
# create a new branch, push changes to new branch and commit

job:
  before_script:
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
  script:
    - if [ `git rev-parse --verify --quiet branch_name` ]; then 
    - echo "F-Droid branch exists, deleting..."
    - git branch -D f-droid 
    - fi
    - echo "Creating new F-Droid branch..."
    - git checkout -b f-droid
    - echo "new version" >> version.txt
    - git add version.txt
    - git commit -m "version some_number_here"
    - git push "https://${GITLAB_USER_NAME}:3ozBDRjysM2dXsDMN4tX@${CI_REPOSITORY_URL#*@}"
  only:
    - tags
