# if there's a new tag, check if there's a branch called F-Droid in GitLab, then delete it if there is
# create a new branch, push changes to new branch and commit

job:
  before_script:
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
  script:
    - var=$(git describe --tags)
    - git fetch
    - if [ -n `git rev-parse --verify --quiet f-droid` ]; then 
    - echo "F-Droid branch exists already..."
    - git checkout f-droid
    - git pull
    - else
    - echo "Creating new F-Droid branch..."
    - git checkout -b f-droid
    - fi
    - version=${var:1}
    - sed -i "s#versionCode appVersionCode#versionCode $version}#" app/build.gradle
    - sed -i "s#versionName appVersionName#versionName $version}#" app/build.gradle
    - git add app/build.gradle
    - git commit -m "update to $var"
    - git push "https://${GITLAB_USER_NAME}:3ozBDRjysM2dXsDMN4tX@${CI_REPOSITORY_URL#*@}"
  only:
    - tags
